/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#191c1d",
        background: "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed-variant": "#00531e",
        "primary-fixed": "#ffdbd1",
        "on-secondary-fixed": "#1a1c1e",
        "on-secondary-fixed-variant": "#454749",
        "on-secondary-container": "#636467",
        "surface-bright": "#f8f9fa",
        surface: "#f8f9fa",
        tertiary: "#006b29",
        "secondary-fixed": "#e2e2e5",
        "primary-fixed-dim": "#ffb59f",
        "on-primary-container": "#fffbff",
        "secondary-container": "#e2e2e5",
        "inverse-primary": "#ffb59f",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-surface": "#191c1d",
        "surface-container-low": "#f3f4f5",
        "surface-container-high": "#e7e8e9",
        "surface-container-lowest": "#ffffff",
        secondary: "#5d5e61",
        "surface-container": "#edeeef",
        "inverse-on-surface": "#f0f1f2",
        "primary-container": "#d63c00",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#3b0a00",
        "on-primary-fixed-variant": "#862200",
        "on-secondary": "#ffffff",
        "outline-variant": "#e5beb3",
        "tertiary-container": "#008735",
        "on-tertiary-container": "#f7fff2",
        primary: "#ab2e00",
        outline: "#916f66",
        "surface-dim": "#d9dadb",
        "on-surface-variant": "#5c4038",
        "tertiary-fixed": "#69ff87",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed-dim": "#3ce36a",
        "surface-tint": "#af3000",
        "secondary-fixed-dim": "#c6c6c9",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#002108",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        md: "16px",
        sm: "8px",
        base: "4px",
        gutter: "16px",
        xl: "40px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "kds-timer": ["Inter"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "kds-timer": [
          "48px",
          { lineHeight: "48px", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}